### ISSUE TITLE
creación de capa controladora para servicio (front-end) cargaDatos

### ISSUE THREAD

**Issue by RominaRomano** [ArgLogan2/Backinmobiliaria#4]
el servicio cargaDatos de front-end dinámico se encarga de obtener del back los datos necesarios para cargar la información en la página de Inicio. En esta primer sprint será necesario crear los métodos getter para la entidad Inmobiliaria la cual contendrá datos de la página de inicio en desarrollo.

**Comment by jpablo903** [comment]
Buenos días, ya está realizado la capa controladora, quedaría lista para probarla, hacer las correcciones o modificaciones necesarias.
